#!/bin/bash
#SBATCH -A gpu
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH -t 04:00:00
#SBATCH -o logs/%x-%j.out

echo "Running on compute node:"
echo $(hostname)
echo "CUDA_VISIBLE_DEVICES is set to: $CUDA_VISIBLE_DEVICES"

mkdir -p logs

# IMPORTANT:
# Set this to an existing attack run directory that already contains:
#   - attack_data.npz
#   - shadow_models/m_actual.npy
#   - precomputed_matrices/influence_data.npz
REUSE_RUN_DIR="/scratch/scholar/kapur16/attacks/10pct_seed42_overfit"

# MCMC-only rerun (no shadow retraining)
python -u shadow_attack.py \
  --checkpoint-dir ./checkpoints/10pct_seed42_overfit \
  --num_shadow_models 64 \
  --num_queries 2000 \
  --prior-prob 0.5 \
  --use-final-model \
  --attack-dir /scratch/scholar/kapur16/attacks \
  --reuse-attack-run /scratch/scholar/kapur16/attacks/10pct_seed42_overfit \
  --analyze-influence